jobs:
  - name: build
    type: runSh
    triggerMode: serial
    allowPublicAccess: false
    runtime:
      container: false
    steps:
      - IN: krddevdays
      - TASK:CONTAINER_NAME_TAG
          - script: >
              CONTAINER_NAME_LATEST=$DOCKER_IMAGE_NAME:latest

              echo $CONTAINER_NAME_LATEST

              if [ ! -z $KRDDEVDAYS_GIT_TAG_NAME ]; then
              CONTAINER_NAME_TAG=$DOCKER_IMAGE_NAME:$KRDDEVDAYS_GIT_TAG_NAME; fi

              echo $CONTAINER_NAME_TAG

              if [ ! -z $KRDDEVDAYS_GIT_BRANCH ]; then
              CONTAINER_NAME_BRANCH=$DOCKER_IMAGE_NAME:$KRDDEVDAYS_GIT_BRANCH;
              fi

              echo $CONTAINER_NAME_BRANCH

              if [ ! -z $_KRDDEVDAYS__COMMIT ]; then
              CONTAINER_NAME_SHA=$DOCKER_IMAGE_NAME:$(echo $_KRDDEVDAYS__COMMIT 
              | awk '{ string=substr($0, 0, 7); print string; }'); fi

              echo $CONTAINER_NAME_SHA

              echo "Building images"

              sudo  docker build ./IN/krddevdays $([ "${KRDDEVDAYS_GIT_BRANCH}" = "master" ] && echo "-t
              $CONTAINER_NAME_LATEST") \
                                 $([ ! -z $ ] && echo "-t $CONTAINER_NAME_TAG") \
                                 $([ ! -z $CONTAINER_NAME_BRANCH ] && echo "-t $CONTAINER_NAME_BRANCH") \
                                 $([ ! -z $CONTAINER_NAME_SHA ] && echo "-t $CONTAINER_NAME_SHA") \
                                 . || exit 1
