jobs:
  - name: build_and_push
    type: runSh
    steps:
      - IN: krddevdays
      - TASK:
          name: "generate container_name"
          runtime:
            options:
              env:
                - DOCKER_IMAGE_NAME: "krddevdays/krd.dev"
          script:
            - >
              if [ "$KRDDEVDAYS_GIT_BRANCH" != "master" ]; then
                CONTAINER_NAME=$DOCKER_IMAGE_NAME:latest;
              elif [[ -n $KRDDEVDAYS_GIT_TAG_NAME ]]; then
                CONTAINER_NAME=$DOCKER_IMAGE_NAME:$KRDDEVDAYS_GIT_TAG_NAME;
              elif [[ -n $KRDDEVDAYS_GIT_BRANCH ]]; then
                CONTAINER_NAME=$DOCKER_IMAGE_NAME:$KRDDEVDAYS_GIT_BRANCH;
              else
                CONTAINER_NAME=$DOCKER_IMAGE_NAME:$(echo $KRDDEVDAYS_COMMIT | awk '{ string=substr($0, 0, 7); print string; }');
              fi
      - TASK:
          name: "build"
          script:
            - >
              cd $(shipctl get_resource_state krddevdays)
              sudo docker build -t "$CONTAINER_NAME" . || exit 1
      - TASK:
          name: "push"
          script:
            - sudo docker push "$CONTAINER_NAME"
