jobs:
  - name: build
    type: runSh
    triggerMode: serial
    allowPublicAccess: false
    runtime:
      container: false
    steps:
      - IN: krddevdays
      - TASK:
        - script: >
            DOCKER_IMAGE_NAME="krddevdays/krd.dev"

            if [ "$KRDDEVDAYS_GIT_BRANCH" != "master" ]; then
              CONTAINER_NAME=$DOCKER_IMAGE_NAME:latest;
            elif [[ -n $KRDDEVDAYS_GIT_TAG_NAME ]]; then
              CONTAINER_NAME=$DOCKER_IMAGE_NAME:$KRDDEVDAYS_GIT_TAG_NAME;
            elif [[ -n $KRDDEVDAYS_GIT_BRANCH ]]; then
              CONTAINER_NAME=$DOCKER_IMAGE_NAME:$KRDDEVDAYS_GIT_BRANCH;
            else
              CONTAINER_NAME=$DOCKER_IMAGE_NAME:$(echo $KRDDEVDAYS_COMMIT | awk '{ string=substr($0, 0, 7); print string; }');
            fi
            
            cd $(shipctl get_resource_state krddevdays)

            sudo docker build -t "$CONTAINER_NAME" ./IN/krddevdays || exit 1
