jobs:
  - name: build
    type: runSh
    triggerMode: serial
    allowPublicAccess: false
    runtime:
      container: false
    steps:
      - IN: krddevdays
      - TASK:
        - script: |
            DOCKER_IMAGE_NAME="krddevdays/krd.dev"
            
            if [ "$KRDDEVDAYS_GIT_BRANCH" -eq "master" ]; then
              CONTAINER_NAME=$DOCKER_IMAGE_NAME:latest;
            elif [ ! -z $KRDDEVDAYS_GIT_TAG_NAME ]; then
              CONTAINER_NAME=$DOCKER_IMAGE_NAME:$KRDDEVDAYS_GIT_TAG_NAME;
            elif [ ! -z $KRDDEVDAYS_GIT_BRANCH ]; then
              CONTAINER_NAME=$DOCKER_IMAGE_NAME:$KRDDEVDAYS_GIT_BRANCH;
            if [ ! -z $_KRDDEVDAYS_COMMIT ]; then
              CONTAINER_NAME=$DOCKER_IMAGE_NAME:$(echo $_KRDDEVDAYS_COMMIT | awk '{ string=substr($0, 0, 7); print string; }');
            fi

            sudo docker build -t "$CONTAINER_NAME" ./IN/krddevdays || exit 1
