resources:
  - name: site
    type: gitRepo
    integration: GitHub
    versionTemplate:
      sourceName: krddevdays/krddevdays.ru
      buildOnCommit: true
      buildOnPullRequest: false
      buildOnPullRequestClose: false
      buildOnRelease: false
      buildOnTagPush: false

  - name: docker_hub
    integration: dockerHub

  - name: docker_image
    type: image
    versionTemplate:
      sourceName: "krddevdays/krd.dev"

jobs:
  - name: build_and_push
    type: runSh     
    steps:
      - IN: site
      - IN: docker_hub
      - TASK:
          script:
            - |
              if [ "${SITE_GIT_BRANCH}" == "master" ]; then
                IMAGE_TAG="latest";
              elif [[ -n $SITE_GIT_TAG_NAME ]]; then
                IMAGE_TAG="${SITE_GIT_TAG_NAME}";
              elif [[ -n $SITE_GIT_BRANCH ]]; then
                IMAGE_TAG="=${SITE_GIT_BRANCH}";
              else
                exit 1
              fi
            - cd $(shipctl get_resource_state site)
            - IMAGE_NAME=$(shipctl get_resource_version_key docker_image "sourceName")
            - docker build -t $IMAGE_NAME:$IMAGE_TAG .
            - docker login -u $DOCKER_HUB_INTEGRATION_USERNAME -p $DOCKER_HUB_INTEGRATION_TOKEN
            - docker push $IMAGE_NAME:$IMAGE_TAG
      - OUT: docker_image
    on_success:
      script:
        - shipctl put_resource_state_multi docker_image "versionName=${IMAGE_TAG}"
